version: "3"

services:
    web-app:
        container_name: webapp
        restart: always
        build:
            context: ./web-app
        ports:
            - "5000:5000"
        networks:
            - default
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - web-app
        networks:
            - default
    websocket:
        container_name: websocket
        restart: always
        build:
            context: ./websocket
        ports:
            - "8080:8080"
        networks:
            - default
    # message-queue:
    #     build:
    #         context: ./message-queue
    
    # fib-calc:
    #     build:
    #         content: ./fib-calc

networks:
    default:
