version: "3"

services:
    web-app:
        container_name: webapp
        restart: always
        build:
            context: ./web-app
        ports:
            - "5000:5000"
        networks:
            - default
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - web-app
        networks:
            - default
    websocket:
        container_name: websocket
        restart: always
        build:
            context: ./websocket
        ports:
            - "8080:8080"
        networks:
            - default
    message-queue:
        container_name: messagequeue
        restart: always
        image: rabbitmq:3-management
        # build:
        #     context: ./message-queue
        ports:
            - "5672:5672"
            - "15672:15672"
        hostname: messagequeue
        networks:
            - default
    fib-calc:
        container_name: fibcalc
        restart: always
        build:
            context: ./fib-calc
        networks:
            - default
        depends_on:
            - messagequeue

networks:
    default:
